export const SHARED_NAMESPACES = {
  providerRegistry: "provider.registry",
  providerStatus: "provider.status",
  providerGoogleSummary: "provider.google.summary",
  providerGithubPulse: "provider.github.pulse",
  providerCreatorStatus: "provider.creator.status",
  mediaNowPlaying: "media.nowPlaying",
  mediaActions: "media.actions",
  automationLastScene: "automation.scene.lastRun",
  automationScenes: "automation.scenes",
  automationFocus: "automation.focus.state",
  agentSelected: "agent.selected",
  agentHealth: "agent.health",
  agentCommands: "agent.commands",
  dashboardFeed: "agent.feed",
} as const;
